### ISSUE TITLE
Milestone 1: Kanban set-up

### ISSUE THREAD

**Issue by Lizdev-05** [hammaazarok/space-ship#25]
Our group has two members, and the tasks have been shared accordingly.
This is the link to our kanban: https://github.com/hammaazarok/space-ship/projects/1

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @Lizdev-05 and @hammaazarok,

✔️ All tasks are assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
